"""
Read in raw CPS data file and structure to be used in future scripts
"""
import pandas as pd
import numpy as np


def h_recs(rec):
    """
    Process each household record in the raw CPS file and

    Parameters
    ----------
    rec: Record from CPS file

    Returns
    -------
    DataFrame with the variables

    """
    record = pd.DataFrame()
    record['hrecord'] = [int(rec[0])]
    record['h_seq'] = [int(rec[1:6])]
    record['hhpos'] = [int(rec[6:8])]
    record['hunits'] = [int(rec[8])]
    record['hefaminc'] = [int(rec[9:11])]
    record['h_respnm'] = [int(rec[11:13])]
    record['h_year'] = [int(rec[13:17])]
    record['h_hhtype'] = [int(rec[19])]
    record['h_numper'] = [int(rec[20:22])]
    record['hnumfam'] = [int(rec[22:24])]
    record['h_type'] = [int(rec[24])]
    record['h_month'] = [int(rec[25:27])]
    record['h_mis'] = [int(rec[28])]
    record['h_hhnum'] = [int(rec[29])]
    record['h_livqrt'] = [int(rec[30:32])]
    record['h_typebc'] = [int(rec[32:34])]
    record['h_tenure'] = [int(rec[34])]
    record['h_telhhd'] = [int(rec[35])]
    record['h_telavl'] = [int(rec[36])]
    record['h_telint'] = [int(rec[37])]
    record['gereg'] = [int(rec[38])]
    record['gestcen'] = [int(rec[39:41])]
    record['gestfips'] = [int(rec[41:43])]
    record['gtcbsa'] = [int(rec[43:48])]
    record['gtco'] = [int(rec[48:51])]
    record['gtcbsast'] = [int(rec[51])]
    record['gtmetsta'] = [int(rec[52])]
    record['gtindvpc'] = [int(rec[53])]
    record['gtcbsasz'] = [int(rec[54])]
    record['gtcsa'] = [int(rec[55:58])]
    record['hunder15'] = [int(rec[59:61])]
    record['hh5to18'] = [int(rec[67:69])]
    record['hhotlun'] = [int(rec[69])]
    record['hhotno'] = [int(rec[70])]
    record['hflunch'] = [int(rec[71])]
    record['hflunno'] = [int(rec[72])]
    record['hpublic'] = [int(rec[73])]
    record['hlorent'] = [int(rec[74])]
    record['hfoodsp'] = [int(rec[75])]
    record['hfoodno'] = [int(rec[76])]
    record['hfoodmo'] = [int(rec[78:80])]
    record['hengast'] = [int(rec[84])]
    record['hengval'] = [int(rec[85:89])]
    record['hinc_ws'] = [int(rec[89])]
    record['hwsval'] = [int(rec[90:97])]
    record['hinc_se'] = [int(rec[97])]
    record['hseval'] = [int(rec[98:105])]
    record['hinc_fr'] = [int(rec[105])]
    record['hfrval'] = [int(rec[106:113])]
    record['hinc_uc'] = [int(rec[113])]
    record['hucval'] = [int(rec[114:121])]
    record['hinc_wc'] = [int(rec[121])]
    record['hwcval'] = [int(rec[122:129])]
    record['hss_yn'] = [int(rec[129])]
    record['hssval'] = [int(rec[130:137])]
    record['hssi_yn'] = [int(rec[137])]
    record['hssival'] = [int(rec[138:144])]
    record['hpaw_yn'] = [int(rec[144])]
    record['hpawval'] = [int(rec[145:151])]
    record['hvet_yn '] = [int(rec[151])]
    record['hvetval'] = [int(rec[152:159])]
    record['hsur_yn '] = [int(rec[159])]
    record['hsurval'] = [int(rec[160:167])]
    record['hdis_yn'] = [int(rec[167])]
    record['hdisval'] = [int(rec[168:175])]
    record['hret_yn'] = [int(rec[175])]
    record['hretval'] = [int(rec[176:183])]
    record['hint_yn'] = [int(rec[183])]
    record['hintval'] = [int(rec[184:191])]
    record['hdiv_yn'] = [int(rec[191])]
    record['hdivval'] = [int(rec[192:199])]
    record['hrnt_yn'] = [int(rec[199])]
    record['hrntval'] = [int(rec[200:207])]
    record['hed_yn'] = [int(rec[207])]
    record['hedval'] = [int(rec[208:215])]
    record['hcsp_yn'] = [int(rec[215])]
    record['hcspval'] = [int(rec[216:223])]
    record['halm_yn'] = [int(rec[223])]
    record['halmval'] = [int(rec[224:231])]
    record['hfin_yn'] = [int(rec[231])]
    record['hfinval'] = [int(rec[232:239])]
    record['hoi_yn'] = [int(rec[239])]
    record['hoival'] = [int(rec[240:247])]
    record['htotval'] = [int(rec[247:255])]
    record['hearnval'] = [int(rec[255:263])]
    record['hothval'] = [int(rec[263:271])]
    record['hhinc'] = [int(rec[271:273])]
    record['hmcare'] = [int(rec[273])]
    record['hmcaid'] = [int(rec[274])]
    record['hchamp'] = [int(rec[275])]
    record['hhi_yn'] = [int(rec[276])]
    record['hhstatus'] = [int(rec[277])]
    record['hunder18'] = [int(rec[278:280])]
    record['htop5pct'] = [int(rec[280])]
    record['hpctcut'] = [int(rec[281:283])]
    record['hsup_wgt'] = [float(rec[286:292] + '.' + rec[292:294])]
    record['h1tenure'] = [int(rec[294])]
    record['h1livqrt'] = [int(rec[296])]
    record['h1telhhd'] = [int(rec[298])]
    record['h1telavl'] = [int(rec[299])]
    record['h1telint'] = [int(rec[300])]
    record['i_hhotlu'] = [int(rec[307])]
    record['i_hhotno'] = [int(rec[308])]
    record['i_hflunc'] = [int(rec[309])]
    record['i_hflunn'] = [int(rec[310])]
    record['i_hpubli'] = [int(rec[311])]
    record['i_hloren'] = [int(rec[312])]
    record['i_hfoods'] = [int(rec[313])]
    record['i_hfdval'] = [int(rec[314])]
    record['i_hfoodn'] = [int(rec[315])]
    record['i_hfoodm'] = [int(rec[316])]
    record['i_hengas'] = [int(rec[317])]
    record['i_hengva'] = [int(rec[318])]
    record['h_idnum2'] = [str(rec[319:324])]
    record['prop_tax'] = [int(rec[331:336])]
    record['housret'] = [int(rec[336:341])]
    record['hrhtype'] = [int(rec[341:343])]
    record['h_idnum1'] = [str(rec[343:358])]
    record['i_hunits'] = [int(rec[358])]
    record['hrpaidcc'] = [int(rec[366])]
    record['hprop_val'] = [int(rec[367:375])]
    record['thprop_val'] = [int(rec[375])]
    record['i_propval'] = [int(rec[376])]
    record['hrnumwic'] = [int(rec[382:384])]
    record['hrwicyn'] = [int(rec[385])]
    record['hfdval'] = [int(rec[386:391])]
    record['tcare_val'] = [int(rec[391])]
    record['care_val'] = [int(rec[392:398])]
    record['i_careval'] = [int(rec[398])]
    record['hpres_mort'] = [int(rec[399])]

    return record
cps = [line.strip().split() for line in
       open('asec2014_pubuse_tax_fix_5x8.dat').readlines()]
print h_recs(cps[0][0])
recs_dict = {}
